os: osx
language: c++
compiler: clang
osx_image: xcode10.1

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOSX_DEPLOYMENT_TARGET=10.12
    - QT_URL=https://github.com/kevinhendricks/BuildSigilOnMac/releases/download/for_sigil_1.0.0/Qt5126.tar.xz

git:
  depth: 3

install:
  - brew install gdrive
  - brew install xz
  - pwd
  - cd ~
  # Retrieve custom Qt
  - wget $QT_URL
  - tar xzf Qt5126.tar.xz
  - export MYQTHOME=${HOME}/Qt5126
  # Add custom Qt to path
  - export PATH=${PATH}:${MYQTHOME}/bin
  # macdeployqt looks for qt plugins in a hard-coded compile-time location
  - sudo mkdir -p /Users/kbhend/Qt5126
  - sudo chown -R travis /Users/kbhend/
  - cp -R ~/Qt5126/plugins /Users/kbhend/Qt5126
  

script:
  - cd ~/build/${TRAVIS_REPO_SLUG}
  - mkdir build && cd build
  - pwd
  - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_CXX_FLAGS=-Wno-inconsistent-missing-override \
      -DCMAKE_PREFIX_PATH=${MYQTHOME}/lib/cmake \
      -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/ ../
  - make -j4
  - make addframeworks
  - cd ./bin
  # Don't make the xz archive on remote PRs
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == true ]]; then
        tar -cJf PageEdit.tar.xz PageEdit.app;
    fi
  - cd ../

after_success:
  # Remote PRs won't set secure variables, so don't try to deploy
  - python3 --version
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == true ]]; then
        python3 ../ci_scripts/macgddeploy.py;
    fi

